In [1]:
# Perceptron_implementation

In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [3]:
# !pip install joblib

In [58]:
class Perceptron: 
    def __init__(self, eta: float=None, epochs: int= None):
        self.weights =np.random.randn(3) * 1e-4  # 1e-4 mean 10^4
        self.eta = eta # learning rate
        self.epochs = epochs
        
    def fit(self, X, y):
        self.X= X
        self.y= y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))] # concatenate matrix with columns 
        print(f"X with bias: \n{x_with_bias}")
              

In [59]:
obj = Perceptron(0.01, 10)

In [60]:
obj.eta

0.01

In [61]:
obj.epochs

10

In [62]:
obj.weights

array([8.04832941e-05, 4.53519216e-05, 2.06459129e-05])

In [63]:
X

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

In [64]:
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [65]:
obj.fit(X, y)

NameError: name 'x_with_bias' is not defined

In [13]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [8]:
X= -np.ones((4,2))
X

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

In [11]:
# Concatenate matrix and columns 

np.c_[X, -np.ones((4,1))]

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [9]:
np.random.randn(3)

array([ 0.26923802, -0.71810152,  2.04282741])

In [ ]:
lr= LinearRegression()
lr.fit(x,y )