In [1]:
# Perceptron_implementation

In [77]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [3]:
# !pip install joblib

In [137]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)

In [138]:
z=34
np.where(z>0, 1, 0)

array(1)

In [139]:
z=-34
np.where(z>0, 1, 0)

array(0)

In [140]:
obj = Perceptron(0.01, 10)

In [141]:
obj.eta

0.01

In [142]:
obj.epochs

10

In [143]:
obj.weights

array([-1.02971440e-07, -6.44288093e-06, -1.32624512e-04])

In [144]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [145]:
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [146]:
obj.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [147]:
# Preparing OR Gate 
OR= {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR= pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [133]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

In [134]:
X, y= prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [135]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [136]:
X, y= prepare_data(df_OR)

ETA= 0.1
EPOCHS= 10

model_or= Perceptron(eta= ETA, epochs= EPOCHS)
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 0 0]
error: 
0   -1
1    0
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.19983197  0.10001258 -0.10002859]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 1.99831975e-01  1.00012580e-01 -2.85862777e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.19983197 0.10001258 0.09997141]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name:

In [150]:
model_or.predict(X=[[1,1]])

array([1])

In [151]:
model_or.predict(X=[[1,0]])

array([1])

In [152]:
model_or.predict(X=[[0,0]])

array([0])

In [ ]:
# Preparing AND Gate 
AND= {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,0,0,1]
}

df_AND= pd.DataFrame(AND)
df_AND